SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for UFLY_METADATA_PROVINCE_BASE
-- ----------------------------
DROP TABLE IF EXISTS `UFLY_METADATA_PROVINCE_BASE`;
CREATE TABLE `UFLY_METADATA_PROVINCE_BASE` (
  `u_id` char(32) NOT NULL COMMENT '主键',
  `u_parent_code` varchar(200) DEFAULT NULL COMMENT '上级编码',
  `u_code` varchar(200) DEFAULT NULL COMMENT '编码',
  `u_name` varchar(200) DEFAULT NULL COMMENT '名称',
  `u_initials` varchar(10) NOT NULL COMMENT '首字母',
  PRIMARY KEY (`u_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='省表';

-- ----------------------------
-- Records of UFLY_METADATA_PROVINCE_BASE
-- ----------------------------
BEGIN;
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('1', 'CN', '110', '北京市', 'B');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('10', 'CN', '320', '江苏省', 'J');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('11', 'CN', '330', '浙江省', 'Z');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('12', 'CN', '340', '安徽省', 'A');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('13', 'CN', '350', '福建省', 'F');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('14', 'CN', '360', '江西省', 'J');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('15', 'CN', '370', '山东省', 'S');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('16', 'CN', '410', '河南省', 'H');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('17', 'CN', '420', '湖北省', 'H');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('18', 'CN', '430', '湖南省', 'H');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('19', 'CN', '440', '广东省', 'G');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('2', 'CN', '120', '天津市', 'T');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('20', 'CN', '450', '广西壮族自治区', 'G');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('21', 'CN', '460', '海南省', 'H');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('22', 'CN', '500', '重庆市', 'C');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('23', 'CN', '510', '四川省', 'S');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('24', 'CN', '520', '贵州省', 'G');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('25', 'CN', '530', '云南省', 'Y');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('26', 'CN', '540', '西藏自治区', 'X');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('27', 'CN', '610', '陕西省', 'S');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('28', 'CN', '620', '甘肃省', 'G');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('29', 'CN', '630', '青海省', 'Q');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('3', 'CN', '130', '河北省', 'H');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('30', 'CN', '640', '宁夏回族自治区', 'N');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('31', 'CN', '650', '新疆维吾尔自治区', 'X');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('4', 'CN', '140', '山西省', 'S');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('5', 'CN', '150', '内蒙古自治区', 'N');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('6', 'CN', '210', '辽宁省', 'L');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('7', 'CN', '220', '吉林省', 'J');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('8', 'CN', '230', '黑龙江省', 'H');
INSERT INTO `UFLY_METADATA_PROVINCE_BASE` VALUES ('9', 'CN', '310', '上海市', 'S');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
